### PR TITLE
Drone

### PR DESCRIPTION
**Pull request by jakolehm**
> [Drone](https://github.com/drone/drone) is a Continuous Delivery system built on container technology. Drone uses a simple yaml configuration file, a superset of docker-compose, to define and execute Pipelines inside Docker containers.

### CODE REVIEW

**Comment by nevalla** [comment]
Maybe out of scope of this PR, but configurable database engine might be good option. http://readme.drone.io/admin/database-engines/

**Comment by nevalla** [comment]
How are admin users configured?

**Comment by jakolehm** [comment]
> How are admin users configured?

Now it prompts github admins/orgs.

**Review by nevalla — APPROVED** [review]
LGTM

**Pull request merged**
