### PR TITLE
fluentd/elasticsearch: Add variables for url scheme/port configuration

### PR DESCRIPTION
**Pull request by wuher**

### CODE REVIEW

**Comment by kke** [comment]
Need to bump the version to something like `0.1.1`

**Comment by wuher** [comment]
In the `fluentd/elasticsearch.yml` file? Do you want me to do that as part of this PR?

**Comment by SpComb** [comment]
> In the fluentd/elasticsearch.yml file? Do you want me to do that as part of this PR?

Yes, the `version: 0.1.0`. The stackfiles in this repo get pushed to the stack registry, and versions are immutable. We can't push the updated stack file unless the `version` also gets bumped.

**Review by jnummelin — APPROVED** [review]
LGTM

@wuher Many thanks for the contribution 👍

**Pull request merged**
